runtime: nodejs20
instance_class: F1

env_variables:
  API_REDIRECT_URI: http://localhost:5173/dashboard
  API_CLIENT_URI: http://localhost:5173
  API_NODE_ENV: development
  API_CLIENT_ID: efecfa4580fd46c4aa1a04799c986e1d
  API_CLIENT_SECRET: 4324744363454d89911c11b05d5dff4d
  API_PORT: 3000

handlers:
  - url: /.*
    script: auto

# Specify the build and start commands
entrypoint: npm start

health_check:
  enable_health_check: True
